// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRjHP1A_YSdoSdMs7D1UOrmEI6ivSSFt0',
    appId: '1:139455821356:web:7017e7858dbcd9e7d60389',
    messagingSenderId: '139455821356',
    projectId: 'lost-found-6493c',
    authDomain: 'lost-found-6493c.firebaseapp.com',
    storageBucket: 'lost-found-6493c.appspot.com',
    measurementId: 'G-5HY1KX7B11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KMwjlobNyuv0rKI-u5nng1nirFGMQLo',
    appId: '1:139455821356:android:f40050a9351d5776d60389',
    messagingSenderId: '139455821356',
    projectId: 'lost-found-6493c',
    storageBucket: 'lost-found-6493c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqefN-MgrhY_MldJrnYV-uk2eyQaRHrc',
    appId: '1:139455821356:ios:a29a1a44a4e60790d60389',
    messagingSenderId: '139455821356',
    projectId: 'lost-found-6493c',
    storageBucket: 'lost-found-6493c.appspot.com',
    iosClientId: '139455821356-obbd8v22stno8fuvhffd4bsdu213nk4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxqefN-MgrhY_MldJrnYV-uk2eyQaRHrc',
    appId: '1:139455821356:ios:a29a1a44a4e60790d60389',
    messagingSenderId: '139455821356',
    projectId: 'lost-found-6493c',
    storageBucket: 'lost-found-6493c.appspot.com',
    iosClientId: '139455821356-obbd8v22stno8fuvhffd4bsdu213nk4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.lostFound',
  );
}
